version: 2.1
jobs:
  try-job:
    macos:
      xcode: 14.0.1
    steps:
      - run: echo "I'm a job named try-job within a workflow named try-workflow."

workflows:
  try-workflow:
    jobs:
      - try-job