version: 2.1
jobs:
  beta-job:
    docker:
      - image: cimg/android:2025.08
    steps:
      - checkout
      - run:
            name: Install Bundler locally
            command: |
              gem install bundler
              bundle config set --local path 'vendor/bundle'
              bundle install

      - run: bash scripts/prepare.sh && bash scripts/beta.sh

workflows:
  beta-workflow:
    jobs:
      - beta-job